### ISSUE TITLE
ErrorModel Data Incorrect

### ISSUE THREAD

**Issue by burakJs** [VB10/vexana#111]
I have the same model for both successful and error cases

```dart
@JsonSerializable(createToJson: false, fieldRename: FieldRename.pascal)
final class AppErrorModel extends INetworkModel<AppErrorModel> {
  const AppErrorModel({
    this.title,
    this.detail,
    this.status,
  });

  final String? title;
  final String? detail;
  final int? status;

  factory AppErrorModel.fromJson(Map<String, dynamic> json) => _$AppErrorModelFromJson(json);

  @override
  AppErrorModel fromJson(Map<String, dynamic> json) => _$AppErrorModelFromJson(json);

  @override
  Map<String, dynamic>? toJson() => {};
}
```

```dart
abstract class BaseResponseModel<T> extends INetworkModel<T> {
  const BaseResponseModel({this.success = false, this.message, this.errorModel});

  final bool success;
  final String? message;
  final AppErrorModel? errorModel;
}
```

```dart
@JsonSerializable(createToJson: false, fieldRename: FieldRename.pascal)
final class LoginResponseModel extends BaseResponseModel<LoginResponseModel> {
  final LoginResponseDataModel? data;

  const LoginResponseModel({
    this.data,
    super.success,
    super.message,
    super.errorModel,
  });

  factory LoginResponseModel.fromJson(Map<String, dynamic> json) => _$LoginResponseModelFromJson(json);

  @override
  LoginResponseModel fromJson(Map<String, dynamic> json) => _$LoginResponseModelFromJson(json);

  @override
  Map<String, dynamic>? toJson() => {};
}
```

Since it is like this, I need to be able to receive my model in case of error. That's why I edited the `receiveDataWhenStatusError` and `validateStatus` values

```dart
NetworkManager _baseNetworkManager() => NetworkManager<EmptyModel>(
        isEnableLogger: true,
        options: BaseOptions(
          baseUrl: baseUrl,
          contentType: ContentType.json.value,
          receiveDataWhenStatusError: true,
          validateStatus: (status) => status! < 500,
        ),
      );
```
When I get an error, I cannot get the status I expect because of the code I specified below in the send method in the package.

```dart
return ResponseModel(
        error: ErrorModel(description: response.data.toString()),
      );
```

- My response:
![image](https://github.com/user-attachments/assets/7408824f-d881-437d-b8ff-d69f62e14dd1)

- The response I received
![image](https://github.com/user-attachments/assets/4e2225e4-e18e-4e17-9763-9c63b9e97dc9)

**Comment by behzodfaiziev** [comment]
@burakJs as one of the solutions we can throw a DioException so it will be handled by catch case.
![image](https://github.com/user-attachments/assets/8feca1ea-9f79-42f8-a960-7c1f58b5e020)

**Comment by burakJs** [comment]
> @burakJs as one of the solutions we can throw a DioException so it will be handled by catch case. ![image](https://private-user-images.githubusercontent.com/63793311/360428323-8feca1ea-9f79-42f8-a960-7c1f58b5e020.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMjk5NTcsIm5iZiI6MTcyNDMyOTY1NywicGF0aCI6Ii82Mzc5MzMxMS8zNjA0MjgzMjMtOGZlY2ExZWEtOWY3OS00MmY4LWE5NjAtN2MxZjU4YjVlMDIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDEyMjczN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg2NTFkYThjODZmNzcxNzAxMDQ5YTVlMjQ5YjQwYTY0Y2Q0ZmY1MmVlNmUzNzI1NTA5ZTVjMjM4ZDI4YWY3NTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3RmqbAZWNPDd8hWw-M20yRIkBarGknpUmncrg0VTQGs)

It seems logical. I will open a PR for this and then test it in my project and share the result here. Thank you very much for the solution suggestion

**Comment by burakJs** [comment]
I tried this solution and i got error model in `response.error.model` thanks for it @behzodfaiziev
