### ISSUE TITLE
Unhandled Exception: LateInitializationError: Field '_retryCount@298188224' has not been initialized.

### ISSUE THREAD

**Issue by hesty** [VB10/vexana#12]
When I was added refresh token business I get an error like this

![Screen Shot 2021-06-03 at 12 39 18](https://user-images.githubusercontent.com/61988280/120623954-dd195580-c468-11eb-9123-847d1109955f.png)

other features are don't have a problem. Can you help me?

**Comment by hesty** [comment]
I think this bug is caused by the variable not being initialized. https://github.com/VB10/vexana/blob/0ec5529295ebeb1e56e4d561ffb9e46be195031d/lib/src/network_manager.dart#L32 https://github.com/VB10/vexana/blob/0ec5529295ebeb1e56e4d561ffb9e46be195031d/lib/src/operation/network_wrapper.dart#L16 so when I initialize the variable from local everything works perfectly 👍

**Comment by VB10** [comment]
supeer, thanks you.i m sory for late as I have very work this week. good job.
