### ISSUE TITLE
how do we retryRequest

### ISSUE THREAD

**Issue by azaderdogan** [VB10/vexana#34]
For example, if I don't have an internet connection and when the connection comes, how can I renew the request without missing it?

**Comment by VB10** [comment]
yo shuld be try retry pakcge from google dev or we can implement this feature on our services. but it's depend for your business logic i think you should be write.
https://pub.dev/packages/retry

**Comment by azaderdogan** [comment]
I think we should add a method called retry to the NetworkManager class. this suggestion is beyond my scope. I may want to do this with the network service I am currently using. maybe a pr request will come
