### ISSUE TITLE
Local tanımlı baseurl ile çalışma

### ISSUE THREAD

**Issue by muratkondu19** [VB10/vexana#37]
Vexana kullanarak oluşturulan bir yapıda baseUrl özelliğine localde tutulan bir string url verildiğinde url görülmemektedir ve ekteki hata oluşmaktadır. 

Kullanımı : 

  INetworkManager networkManager = NetworkManager(
      isEnableLogger: true,
      options: BaseOptions(
          baseUrl: LocaleManager.instance
              .getStringValue(PreferencesKeys.SERVICE_URL)));

![image](https://user-images.githubusercontent.com/58566276/177004676-b9c75c91-e3cc-4a77-929c-486ab2bbb3c1.png)

**Comment by AhmetMelihSerter** [comment]
Merhaba. 

Url bir `http://` etiketi ile başlamalıdır.

İyi Çalışmalar.

**Comment by VB10** [comment]
@AhmetMelihSerter tseekkruler
