### ISSUE TITLE
Vexana Cache return Statuss success data null

### ISSUE THREAD

**Issue by kasapiniz** [VB10/vexana#39]
![cache](https://user-images.githubusercontent.com/72016623/178919719-cbc19565-2e24-4c00-860f-07b294b3be96.PNG)
Tek request'de datayı cache'leyebiliyorum. ama aynı anda iki farklı function'da cacheleme işlemi yapamıyorum. kullanıcı bilgilerini ve postlarını cachelemek istediğim de postların statuss'ü success dönüyor ama içi boş oluyor.  tek bir bilgiyi cachelemek istersem sorunsuz çalışıyor.

**Comment by VB10** [comment]
cacheleme id ile dogru orantili calisiyor burada bir sorun olduysa muhmtelen idler ayni gelmistir ornek json datalarini bize atarsan bakalim simdlik kapatiyorum
