### ISSUE TITLE
Type 'Uint8List' not found

### ISSUE THREAD

**Issue by emirbagdatli** [VB10/vexana#43]
Selamlar,
downloadFileSimple isimli function bir anda hata vermeye başladı sebebi ne olabilir anlamadım.

![Screenshot at Jul 28 23-42-15](https://user-images.githubusercontent.com/65565581/181633634-a9180b40-14db-468d-95d1-22b460879ab1.png)

**Comment by VB10** [comment]
3.0.1 de fixledim teşekkürler
