### ISSUE TITLE
How to fetch list of primitive types?

### ISSUE THREAD

**Issue by hasaneke** [VB10/vexana#45]
Response from the API is only a list of primitive types which looks like this.
[
"a",
"b",
"c",
"d",
]
How can I fetch this with Vexana? (response is just a list of string. It doesn`t have names or curly braces)

**Comment by kadirbekar** [comment]
Have you tried sendPrimitive request? 

more detail: https://github.com/VB10/vexana/blob/master/lib/src/network_manager.dart

At the bottom of the page.
