### ISSUE TITLE
NoNetwork ile ilgili context sorunu

### ISSUE THREAD

**Issue by mehmetozdd** [VB10/vexana#56]
Merhaba hocam saygılar öncelikle. Architecture serinizle paralel bir şekilde kendimi geliştirmek için yazdığım bir uygulamada internetin kesildiği zamanda gösterilecek Popup vb durumları entegre etmeye çalışıyorum. Bir kaç yöntem denedim connectivity_plus kütüphanesini eklemeye çalıştığım zaman Vexana ile birlikte kullanıldığında hata meydana geliyor. Başka bir yöntem olarak vexana'nın sağladığı Nonetwork yapısını kullanmaya çalıştım .Vexana_manager.dart dosyasında(Architecture serisindeki) nonetwork'un istediği context'i sağlayamıyorum yardımcı olursanız sevinirim.

**Comment by VB10** [comment]
bizim ornekler proje icinde no network ornekleri var ona bakabilrisin example artinda
