### ISSUE TITLE
FormData problemi

### ISSUE THREAD

**Issue by mehmetozdd** [VB10/vexana#59]
Aldığım hatayı stackoverflowda yazdım fakat herhangi bi cevap alamıyorum şuan eğer yardım etmek isteyen varsa mutlu olurum vexana kullanırken formdatayı nasıl yollayacağımı bilmiyorum 
https://stackoverflow.com/questions/75411197/formdata-request-with-dio

**Comment by kadirbekar** [comment]
@mehmetozdd bu örneği inceleme fırsatınız oldu mu?

https://github.com/VB10/vexana/pull/48

**Comment by kadirbekar** [comment]
Estağfurullah, rica ederim

**Comment by VB10** [comment]
@kadirbekar tesekkurler
