### ISSUE TITLE
Windows Web Platform Dio Desteği

### ISSUE THREAD

**Issue by Tannyll** [VB10/vexana#6]
Windows web ortamın'da DIO desteği bulunmuyor. Dio için web ortamına desteklenmesinin yararlı olabileceğini düşünüyorum.

DioError [DioErrorType.DEFAULT]: Unsupported operation: Platform._version

**Comment by Tannyll** [comment]
Bu konu ile ilgili destek sağlanır mı? 
#vexana: any

**Comment by VB10** [comment]
evet tum platformlara destek verecek hale getiriyorum cok yakinda

**Comment by VB10** [comment]
@Tannyll yeni versiyonda web support geldi kolay gelsin
