### ISSUE TITLE
Getting response.error.model null for Response Code 400

### ISSUE THREAD

**Issue by pravin-sorigin** [VB10/vexana#63]
Hi,
I'm using this library since one year in our product.
And just noticed that in `vexana: 3.3.2`, I'm getting response.error.model as a null for status code 400.

I can see the response in the interceptor but not getting into the error model.

Please help, How can I get error model?

**Comment by VB10** [comment]
@pravin-sorigin hi
Please update your version to the latest (3.4.1), and your implementation should be as follows:
![image](https://user-images.githubusercontent.com/17102578/225585523-a6aa7dd9-0d16-431e-b0db-4ad89cd19504.png)

`dart
class ApiBaseError extends INetworkModel<ApiBaseError> {
  ApiBaseError({
    this.errors,
  });
`

**Comment by pravin-sorigin** [comment]
@VB10 Thanks.
I resolved it by add below two params.
<img width="351" alt="image" src="https://user-images.githubusercontent.com/100113424/225598603-fdeb96fe-432e-46df-9f45-a08765aac2a7.png">
