### ISSUE TITLE
Update connectivity_plus dependency

### ISSUE THREAD

**Issue by behzodfaiziev** [VB10/vexana#66]
Hello,
I am going to update connectivity_plus package which solves some issues in newer version. However, since it also dependes on version 2.3.5, I cound not update it. 

Can I send a PR to update version of connectivity_plus to latest vesrion in vexana? 

Thank you!

**Comment by MehmetKaranlik** [comment]
@behzodfaiziev  You can use master for now, this issue solved there. We will send new version to pub asap.
