### ISSUE TITLE
Bloc Eğitimi İçeriğinde kullanılan vexana hk.

### ISSUE THREAD

**Issue by niyazimustafa** [VB10/vexana#67]
Future<IResponseModel<TokenModel?>?> login(LoginModel model) async {
    return await networkManager.send<TokenModel, TokenModel>(
      'api/login',
      data: model,
      parseModel: TokenModel(),
      method: RequestType.POST,
    );
  }

Kullanımında The type 'IResponseModel' is declared with 2 type parameters, but 1 type arguments were given.
Try adjusting the number of type arguments to match the number of type parameters kızmaktadır.

**Comment by MehmetKaranlik** [comment]
```dart
import 'package:vexana/vexana.dart';

abstract class IResponseModel<T, E extends INetworkModel<E>?> {
  T data;
  IErrorModel<E>? error;

  IResponseModel(this.data, this.error);
}
IResponseModel 2 generic argümana sahip bir class.
Birincisi almak istediğin datanın türü, ikinciside olası bir hatada castlenecek olan ErrorModelin türü.
Sen sadece TokenModel? verdiğin için kızıyor. Birşey vermek istemiyorsan EmptyModele castleyebilirsin.
```
