### ISSUE TITLE
Parsing of EmptyParseModel throws error if response.body contains List

### ISSUE THREAD

**Issue by behzodfaiziev** [VB10/vexana#76]
```
 final response = await manager.send<EmptyModel, EmptyModel>(
        APIConst.example,
        parseModel: EmptyModel(),
        method: RequestType.POST,
        data: example.toJson(),
      );
```

 ## Partially Working Case

### Expected result: 
response.data = EmptyModel(name: "anydata");

### Actual result:
response.data = EmptyModel(name: null);  ``// it doesn't give name, but at least data is not null``

#### Expected result: 
response.data = EmptyModel(name: "anydata");

#### Actual result:
response.data = null;

It throws an error: 
`
Parse Error: type 'List<EmptyModel>' is not a subtype of type 'EmptyModel' in type cast - response body: [{example: 1}] T model: EmptyParseModel , R model: EmptyParseModel 
`

## What is next:
I found a solution but I need to make sure that it works. After a while I am going to create PR if I succesfully test it

**Comment by behzodfaiziev** [comment]
@VB10 I've fixed this issue. Since I have already opened PR before, changes were sent to #75. If the solution is not good, feel free to request changes

**Comment by MehmetKaranlik** [comment]
@VB10 
@behzodfaiziev 
Since its merge im closing this issue.
