### ISSUE TITLE
In-Memory Caching for Responses 

### ISSUE THREAD

**Issue by MehmetKaranlik** [VB10/vexana#87]
Vexana already includes caching via local caching mechanism, i believe either we can improve this to in-memory caching for fast read/write access and safety issues. Or we can add another caching options while retaining the current one.

**Comment by MehmetKaranlik** [comment]
@VB10

**Comment by VB10** [comment]
acutally i dont want to keep our caching data to in memory. it most of depends on application and porbably getting some issues after this implementation. For this reason without you can create your custom caching class like VBCache and give it in vexana. it would be better then our management.
