### ISSUE TITLE
INetworkModel const constructor

### ISSUE THREAD

**Issue by MehmetKaranlik** [VB10/vexana#91]
There is nothing preventing INetworkModel abstract class to have const constructor but its not implemented. So any child class extends  can't have const constructor. I suggest we add const constructor to INetworkModel. @VB10

**Comment by VB10** [comment]
thanks your feedback i've added for this. You can able to use with new version

**Comment by VB10** [comment]
<img width="464" alt="image" src="https://github.com/VB10/vexana/assets/17102578/545a6bc8-4689-47b1-971b-30c514520308">

**Comment by VB10** [comment]
completed
