### ISSUE TITLE
Bearer Token ekleme

### ISSUE THREAD

**Issue by dogankstu** [VB10/vexana#96]
Vexana kullanımında slpash ve login sayfaları haricinde servise token göndermek istiyorum. Nasıl yapabilirim?

**Comment by kadirbekar** [comment]
Uygulama genelinde kullanmak için bir network manager objesi oluşturduğunu varsayalım.

class NetworkService {

    final networkManager = NetworkManager(
       ...
       ...
    );
    
    // Network katmanı için gerekli konfigürasyonları yaptığını varsayalım, (interceptor, BaseOptions vs.)
    
    void addTokenToHeader(String token) {
        networkManager.addBaseHeader(MapEntry('Bearer', '$token'));
    }
    
}

Login işlemini başarılı bir şekilde gerçekleştirdikten sonra token bilgisi servisten geldi.
NetworkService içerisinde tanımlı olan networkManager objesine erişip -> 
NetworkService.instance.networkManager.addTokenToHeader('servistenGelenToken'); diyerek ekleyebilirsin. @dogankstu

**Comment by VB10** [comment]
@kadirbekar teşekkür ederim
